### ISSUE TITLE
full jmdict

### ISSUE THREAD

**Issue by epistularum** [ezhmd/cham-jp-deck#1]
I would like to convert the full jmdict project and not only frequent words, is it possible?

**Comment by ezhmd** [comment]
Hello @epistularum,

Yes, it's possible. I tried that while developing this code.

I think the part that you need to edit is around these lines in code.js
```js
    // Add raw from JMdict Freq
    
    raw.vocab_jmdict_freq = [];
    
    JMdict.forEach(function(entry) {
    
        if (entry.k_ele) entry.k_ele.forEach(function (k_ele) {
    
            // if it has freq tag, add to the collection
            if (k_ele.ke_pri) {
                raw.vocab_jmdict_freq.push(k_ele.keb);
            }
        });
    });
```

Remove the `if (k_ele.ke_pri)` conditional statement, hence it will import all jmdict words with kanji.

**Comment by epistularum** [comment]
Thank you very much, I'll give it a spin!
